name:                nix-test
version:             0.1.0.0
github:              "alexeyraga/nix-test"
license:             BSD3
author:              "Alexey Raga"
maintainer:          "alexey.raga@gmail.com"
copyright:           "Alexey Raga"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexeyraga/nix-test#readme>

dependencies:
- base >= 4.7 && < 5
- lens

library:
  source-dirs: src

executables:
  nix-test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nix-test

tests:
  nix-test-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nix-test
